# Generated by Django 5.2 on 2026-07-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='domain',
            field=models.CharField(unique=True),
        ),
    ]
